
modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Kirderf/compactxpbottles/issues"
license="All Rights Reserved unless otherwise explicitly stated."

[[mods]] #mandatory
modId="compactxpbottles"
version="1.3.2"
displayName="Compact Experience Bottles" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/compactxpbottles"

#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI

credits="Thanks to presmuffin123"

authors="Kirderf"

description='''
Compact Experience Bottles is created by request at minecraftforum.net. Want to support Kirderf, head over to curseforge and show your support.
'''

