# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# The version of the mod loader required - this uses standard Maven version range syntax. check the @Mod annotation for more details.
loaderVersion="[4,)" #mandatory

issueTrackerURL="https://github.com/Kirderf/compactxpbottles/issues"
license="All Rights Reserved unless otherwise explicitly stated."

[[mods]] #mandatory
modId="compactxpbottles"
version="${mod_version}"
displayName="Compact Experience Bottles" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
updateJSONURL="https://curseupdate.com/349327/compactxpbottles?ml=neoforge" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/compactxpbottles"

#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI

credits="Thanks to presmuffin123"

authors="Kirderf"

description='''
Compact Experience Bottles is created by request at minecraftforum.net. Want to support Kirderf, head over to curseforge and show your support.
'''
