
modLoader="javafml"
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/Kirderf/compactxpbottles/issues"
[[mods]] #mandatory
modId="compactxpbottles"
version="1.0.2"

 # A display name for the mod
displayName="Compact Experience Bottles" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI

displayURL="https://www.curseforge.com/minecraft/mc-mods/compactxpbottles"

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI

credits="Thanks to presmuffin123"

# A text field displayed in the mod UI

authors="Kirderf"

# The description text for the mod (multi line!) (#mandatory)

description='''
Compact Experience Bottles is created by request at minecraftforum.net. Want to support Kirderf, head over to curseforge and show your support.
'''

